### ISSUE TITLE
Create mission statement / description

### ISSUE THREAD

**Issue by lukefretwell** [GovSafe/govsafe.github.io#3]

**Comment by gregelin** [comment]
Audience?
- People working in government who need to understand how to (continuously better the) protect the people's data online.

**Comment by gregelin** [comment]
Not Audience
- existing cyber security experts
- specialists

**Comment by lukefretwell** [comment]
@gregelin created shared doc here:

https://docs.google.com/document/d/18gsLntX4qh1FnLjuFAgn1ruff3Mv26vXckkD4KW14ws/edit?usp=sharing
